/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define STRVR (*((uint32_t*)0xE000E014))
#define STCSR (*((uint32_t*)0xE000E010))


#define DEMCR           (*(volatile uint32_t*)0xE000EDFC)
#define DWT_CTRL        (*(volatile uint32_t*)0xE0001000)
#define DWT_CYCCNT      (*(volatile uint32_t*)0xE0001004)

void timestamp_init(void)
{
    /* Enable trace */
    DEMCR |= (1 << 24);

    /* Reset counter */
    DWT_CYCCNT = 0;

    /* Enable cycle counter */
    DWT_CTRL |= (1 << 0);
}

volatile uint32_t timestamp;
void SysTick_Handler(void){
	uint32_t curr_timestamp = DWT_CYCCNT;
	uint32_t time = (curr_timestamp-timestamp)/168.0f;
	timestamp = DWT_CYCCNT;
}


int main(void)
{
    /* Loop forever */
	timestamp_init();
	timestamp = DWT_CYCCNT;
	STRVR = 168000-1;
	STCSR |= 0x7;
	timestamp = DWT_CYCCNT;
	for(;;);
}

